import { z } from "zod";

const envSchema = z.object({
  NODE_ENV: z.string().default("development"),
  NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:3000"),
  DATABASE_URL: z.string().min(1).optional(),
  DEFAULT_AGENT_EMAIL: z.string().email().default("demo@estatepilot.ai"),
  OPENAI_API_KEY: z.string().optional(),
  OPENAI_MODEL_TEXT: z.string().default("gpt-4o-mini"),
  OPENAI_MODEL_VISION: z.string().default("gpt-4o-mini"),
  RESEND_API_KEY: z.string().optional(),
  RESEND_FROM_EMAIL: z.string().min(3).optional(),
  MAX_UPLOAD_MB: z.coerce.number().positive().default(25),
  STORAGE_DRIVER: z.enum(["local", "r2", "s3"]).default("local"),
  STORAGE_PUBLIC_BASE_URL: z.string().optional(),
  R2_ACCOUNT_ID: z.string().optional(),
  R2_ACCESS_KEY_ID: z.string().optional(),
  R2_SECRET_ACCESS_KEY: z.string().optional(),
  R2_BUCKET: z.string().optional(),
  STRIPE_SECRET_KEY: z.string().optional(),
  BARION_POS_KEY: z.string().optional(),
  SZAMLAZZ_API_KEY: z.string().optional(),
  POSTHOG_KEY: z.string().optional(),
  WEBHOOK_SECRET: z.string().optional(),
  DEV_AUTH_ENABLED: z.coerce.boolean().default(true),

  AUTH_PROVIDER: z.enum(["dev", "clerk", "authjs"]).default("dev"),
  CLERK_SECRET_KEY: z.string().optional(),
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string().optional(),
  AUTH_SECRET: z.string().optional(),
  APP_ENV: z.enum(["local", "preview", "production"]).default("local"),
  APP_REGION: z.string().default("eu-central-1"),
  SENTRY_DSN: z.string().optional(),
  STRIPE_WEBHOOK_SECRET: z.string().optional(),
  BARION_ENV: z.enum(["sandbox", "production"]).default("sandbox"),
  GOOGLE_CALENDAR_CLIENT_ID: z.string().optional(),
  GOOGLE_CALENDAR_CLIENT_SECRET: z.string().optional(),
  GOOGLE_CALENDAR_REDIRECT_URI: z.string().url().optional(),
  PUBLIC_UPLOADS_REQUIRE_APPROVAL: z.coerce.boolean().default(false),

  REQUIRE_PUBLISH_CHECKLIST: z.coerce.boolean().default(true),
  PORTAL_EXPORT_MODE: z.enum(["mock", "file", "api"]).default("mock"),
  ENCRYPTION_KEY: z.string().optional(),
  PUBLIC_DEMO_RESET_ENABLED: z.coerce.boolean().default(false),
  RELEASE_COMMIT_SHA: z.string().optional(),
  PILOT_OWNER_EMAIL: z.string().email().default("pilot@estatepilot.ai"),
  METERING_CURRENCY: z.string().default("HUF"),
  ENABLE_STRICT_RELEASE_GATES: z.coerce.boolean().default(false),
});

export const env = envSchema.parse({
  NODE_ENV: process.env.NODE_ENV,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  DATABASE_URL: process.env.DATABASE_URL,
  DEFAULT_AGENT_EMAIL: process.env.DEFAULT_AGENT_EMAIL,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  OPENAI_MODEL_TEXT: process.env.OPENAI_MODEL_TEXT,
  OPENAI_MODEL_VISION: process.env.OPENAI_MODEL_VISION,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  RESEND_FROM_EMAIL: process.env.RESEND_FROM_EMAIL,
  MAX_UPLOAD_MB: process.env.MAX_UPLOAD_MB,
  STORAGE_DRIVER: process.env.STORAGE_DRIVER,
  STORAGE_PUBLIC_BASE_URL: process.env.STORAGE_PUBLIC_BASE_URL,
  R2_ACCOUNT_ID: process.env.R2_ACCOUNT_ID,
  R2_ACCESS_KEY_ID: process.env.R2_ACCESS_KEY_ID,
  R2_SECRET_ACCESS_KEY: process.env.R2_SECRET_ACCESS_KEY,
  R2_BUCKET: process.env.R2_BUCKET,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  BARION_POS_KEY: process.env.BARION_POS_KEY,
  SZAMLAZZ_API_KEY: process.env.SZAMLAZZ_API_KEY,
  POSTHOG_KEY: process.env.POSTHOG_KEY,
  WEBHOOK_SECRET: process.env.WEBHOOK_SECRET,
  DEV_AUTH_ENABLED: process.env.DEV_AUTH_ENABLED,
  AUTH_PROVIDER: process.env.AUTH_PROVIDER,
  CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
  AUTH_SECRET: process.env.AUTH_SECRET,
  APP_ENV: process.env.APP_ENV,
  APP_REGION: process.env.APP_REGION,
  SENTRY_DSN: process.env.SENTRY_DSN,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  BARION_ENV: process.env.BARION_ENV,
  GOOGLE_CALENDAR_CLIENT_ID: process.env.GOOGLE_CALENDAR_CLIENT_ID,
  GOOGLE_CALENDAR_CLIENT_SECRET: process.env.GOOGLE_CALENDAR_CLIENT_SECRET,
  GOOGLE_CALENDAR_REDIRECT_URI: process.env.GOOGLE_CALENDAR_REDIRECT_URI,
  PUBLIC_UPLOADS_REQUIRE_APPROVAL: process.env.PUBLIC_UPLOADS_REQUIRE_APPROVAL,
  REQUIRE_PUBLISH_CHECKLIST: process.env.REQUIRE_PUBLISH_CHECKLIST,
  PORTAL_EXPORT_MODE: process.env.PORTAL_EXPORT_MODE,
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
  PUBLIC_DEMO_RESET_ENABLED: process.env.PUBLIC_DEMO_RESET_ENABLED,
  RELEASE_COMMIT_SHA: process.env.RELEASE_COMMIT_SHA,
  PILOT_OWNER_EMAIL: process.env.PILOT_OWNER_EMAIL,
  METERING_CURRENCY: process.env.METERING_CURRENCY,
  ENABLE_STRICT_RELEASE_GATES: process.env.ENABLE_STRICT_RELEASE_GATES
});

export function requireEnv(name: keyof typeof env) {
  const value = env[name];
  if (!value) throw new Error(`Missing required env var: ${name}`);
  return value;
}
